use_frameworks!

platform :ios, '11.0'

target 'Z3Profile_Example' do
  pod 'Z3Profile', :path => '../'
  pod 'Z3CommonLib', :path => '../../Z3CommonLib'
  pod 'Z3DBService', :path => '../../Z3DBService'
  pod 'Z3LocationService', :path => '../../Z3LocationService'
  pod 'CoordinateTransform', :path => '../../CoordinateTransform'
end
