use_frameworks!

platform :ios, '8.0'

target 'Z3Profile_Example' do
  pod 'Z3Profile', :path => '../'

  target 'Z3Profile_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
